version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
   runtime-versions:
    java: corretto11
  build:
    commands:
     - echo Build started on `date`
     - gradle build --debug
artifacts:
  type: zip
  files:
    - 'build/libs/*.war'